apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-project
  labels:
    app: devsecops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-project
  template:
    metadata:
      labels:
        app: devsecops-project
    spec:
      containers:
        - name: devsecops-project
          image: chiomavee/devsecops-app:v21
          ports:
            - containerPort: 9090
