apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-project
  labels:
    app: devsecops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-project
  template:
    metadata:
      labels:
        app: devsecops-project
    spec:
      containers:
      - name: devsecops-project
        image: ngozin/devsecops-project:12
        ports:
        - containerPort: 8080