apiVersion: v1
kind: Service
metadata:
  name: devsecops-project
  labels:
    app: devsecops-project
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 31001  # Changed to avoid conflict with Jenkins
  selector:
    app: devsecops-project
